language: node_js
node_js:
  - 'node'
env:
  global:
    - GH_REF: github.com/ronzeidman/ng2-ui-auth
script:
  - npm run build
after_success:
jobs:
  include:
    - stage: npm release
      node_js: 'node'
      script:
        - npm run build
      before_deploy:
        - cd dist/ng2-ui-auth
      deploy:
        provider: npm
        email: 'ron.zeidman@gmail.com'
        api_key: '$NPM_API_KEY'
        skip_cleanup: true
        on:
          tags: true
