language: node_js
node_js:
- '8'
env:
  global:
  - GH_REF: github.com/ronzeidman/ng2-ui-auth
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run build
after_success:
before_deploy:
- cd dist/ng2-ui-auth
# deploy:
#    provider: npm
#    email: "ron.zeidman@gmail.com"
#    api_key: "$NPM_TOKEN"
#    on:
#      tags: true
